<?php

/**
 * @author Sergiusz Michalik <sergiusz.michalik@xsolve.pl>
 */

namespace Tatusiowo\DemoBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Tatusiowo\DemoBundle\Entity\Activity;

class LoadActivityData extends AbstractFixture implements OrderedFixtureInterface
{
    /**
     * Load data fixtures with the passed EntityManager
     *
     * @param ObjectManager $manager
     */
    function load(ObjectManager $manager)
    {
        $activitiesData = [
            ["title" => "In ornare sagittis felis.", "timeFrom" => 12, "timeTo" => 177, "ageFrom" => 4, "ageTo" => 7, "outdoor" => false, "indoor" => true, "fun" => 2, "creativity" => 4, "effort" => 3, "description" => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras", "approved" => true],
            ["title" => "nunc risus varius orci,", "timeFrom" => 18, "timeTo" => 145, "ageFrom" => 4, "ageTo" => 11, "outdoor" => true, "indoor" => true, "fun" => 5, "creativity" => 5, "effort" => 3, "description" => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum", "approved" => true],
            ["title" => "mollis non, cursus non,", "timeFrom" => 5, "timeTo" => 125, "ageFrom" => 2, "ageTo" => 14, "outdoor" => false, "indoor" => true, "fun" => 3, "creativity" => 3, "effort" => 2, "description" => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis", "approved" => true],
            ["title" => "blandit at, nisi. Cum", "timeFrom" => 17, "timeTo" => 115, "ageFrom" => 3, "ageTo" => 11, "outdoor" => false, "indoor" => true, "fun" => 4, "creativity" => 3, "effort" => 4, "description" => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus.", "approved" => false],
            ["title" => "eu nibh vulputate mauris", "timeFrom" => 18, "timeTo" => 91, "ageFrom" => 4, "ageTo" => 6, "outdoor" => false, "indoor" => true, "fun" => 5, "creativity" => 2, "effort" => 5, "description" => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula", "approved" => false],
            ["title" => "ornare, libero at auctor", "timeFrom" => 9, "timeTo" => 48, "ageFrom" => 2, "ageTo" => 8, "outdoor" => true, "indoor" => true, "fun" => 3, "creativity" => 4, "effort" => 5, "description" => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a,", "approved" => true],
            ["title" => "Praesent eu nulla at", "timeFrom" => 18, "timeTo" => 116, "ageFrom" => 1, "ageTo" => 11, "outdoor" => true, "indoor" => true, "fun" => 2, "creativity" => 2, "effort" => 2, "description" => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a,", "approved" => true],
            ["title" => "id ante dictum cursus.", "timeFrom" => 15, "timeTo" => 118, "ageFrom" => 2, "ageTo" => 11, "outdoor" => false, "indoor" => true, "fun" => 1, "creativity" => 5, "effort" => 4, "description" => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper", "approved" => true],
            ["title" => "quam vel sapien imperdiet", "timeFrom" => 5, "timeTo" => 142, "ageFrom" => 2, "ageTo" => 7, "outdoor" => true, "indoor" => false, "fun" => 3, "creativity" => 3, "effort" => 3, "description" => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras", "approved" => false],
            ["title" => "elit, dictum eu, eleifend", "timeFrom" => 5, "timeTo" => 135, "ageFrom" => 2, "ageTo" => 7, "outdoor" => true, "indoor" => false, "fun" => 2, "creativity" => 4, "effort" => 1, "description" => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi.", "approved" => true],
            ["title" => "varius. Nam porttitor scelerisque", "timeFrom" => 5, "timeTo" => 162, "ageFrom" => 2, "ageTo" => 14, "outdoor" => true, "indoor" => true, "fun" => 1, "creativity" => 4, "effort" => 2, "description" => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae,", "approved" => true],
            ["title" => "et magnis dis parturient", "timeFrom" => 15, "timeTo" => 53, "ageFrom" => 5, "ageTo" => 13, "outdoor" => false, "indoor" => true, "fun" => 1, "creativity" => 1, "effort" => 3, "description" => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu", "approved" => false],
            ["title" => "Aliquam adipiscing lobortis risus.", "timeFrom" => 13, "timeTo" => 98, "ageFrom" => 2, "ageTo" => 14, "outdoor" => true, "indoor" => false, "fun" => 5, "creativity" => 3, "effort" => 5, "description" => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut", "approved" => false],
            ["title" => "sed pede nec ante", "timeFrom" => 18, "timeTo" => 77, "ageFrom" => 1, "ageTo" => 10, "outdoor" => true, "indoor" => true, "fun" => 5, "creativity" => 3, "effort" => 4, "description" => "Lorem ipsum dolor sit amet, consectetuer", "approved" => false],
            ["title" => "lobortis quis, pede. Suspendisse", "timeFrom" => 8, "timeTo" => 129, "ageFrom" => 1, "ageTo" => 10, "outdoor" => true, "indoor" => false, "fun" => 4, "creativity" => 3, "effort" => 5, "description" => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet", "approved" => false],
            ["title" => "a, scelerisque sed, sapien.", "timeFrom" => 12, "timeTo" => 86, "ageFrom" => 4, "ageTo" => 13, "outdoor" => false, "indoor" => true, "fun" => 1, "creativity" => 3, "effort" => 5, "description" => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu", "approved" => false],
            ["title" => "metus. In nec orci.", "timeFrom" => 16, "timeTo" => 80, "ageFrom" => 1, "ageTo" => 13, "outdoor" => true, "indoor" => true, "fun" => 5, "creativity" => 4, "effort" => 4, "description" => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut", "approved" => true],
            ["title" => "Vivamus sit amet risus.", "timeFrom" => 20, "timeTo" => 134, "ageFrom" => 1, "ageTo" => 11, "outdoor" => true, "indoor" => true, "fun" => 4, "creativity" => 4, "effort" => 5, "description" => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus", "approved" => true],
            ["title" => "at sem molestie sodales.", "timeFrom" => 18, "timeTo" => 85, "ageFrom" => 1, "ageTo" => 5, "outdoor" => false, "indoor" => true, "fun" => 1, "creativity" => 5, "effort" => 4, "description" => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida", "approved" => true],
            ["title" => "convallis ligula. Donec luctus", "timeFrom" => 5, "timeTo" => 64, "ageFrom" => 3, "ageTo" => 12, "outdoor" => false, "indoor" => true, "fun" => 4, "creativity" => 5, "effort" => 1, "description" => "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis", "approved" => false]
        ];

        foreach ($activitiesData as $k => $data) {
            $activity = new Activity();
            $date = new \DateTime();
            $date->setTimestamp((rand(time() - 10000000, time())));

            $image = $this->getReference(sprintf('image-%d', $k));

            $activity
                ->setTitle($data['title'])
                ->setTimeFrom($data['timeFrom'])
                ->setTimeTo($data['timeTo'])
                ->setAgeFrom($data['ageFrom'])
                ->setAgeTo($data['ageTo'])
                ->setOutdoor($data['outdoor'])
                ->setIndoor($data['indoor'])
                ->setFun($data['fun'])
                ->setCreativity($data['creativity'])
                ->setEffort($data['effort'])
                ->setDescription($data['description'])
                ->setApproved($data['approved'])
                ->setCreatedAt($date)
                ->setImage($image)
            ;

            $activitiesIndex[] = $k;
            $this->addReference(sprintf('activity-%d', $k), $activity);

            $manager->persist($activity);
        }

        $manager->flush();
    }

    /**
     * Get the order of this fixture
     *
     * @return integer
     */
    function getOrder()
    {
        return 2;
    }
} 
